### ISSUE TITLE
Querying optional reference field with null value causes exception

### ISSUE THREAD

**Issue by advancingu** [contentlab-sh/contentlab#26]
# Preconditions

## Schema
```graphql
directive @Entry on OBJECT

type MyEntry @Entry {
    id: ID!
    name: String
    reference: OtherEntry
}

type OtherEntry @Entry {
    id: ID!
    foo: String
}
```

## Entry
```yaml
metadata:
  type: MyEntry
data:
  name: Test
  reference: null
```

# Actual behavior
Trying to query field `reference` causes exception.

# Expected behavior
Querying `reference` returns a value of `null`.
